import { expect, test } from '@playwright/test'

test('arcade checkpoint retries the same transcript and restores the acknowledged simulation', async ({ page }) => {
  await page.goto('/ui-test')
  await page.clock.install()
  await page.getByRole('button', { name: 'Test arcade checkpoint' }).click()
  await expect(page.getByText('Arcade countdown: 3')).toBeVisible()
  await page.clock.runFor(3500)
  await page.getByRole('button', { name: 'Jump arcade', exact: true }).focus()
  await page.keyboard.press('Space')
  await page.clock.runFor(5000)
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('Progress could not be saved')
  const pausedTick = await page.getByTestId('arcade-tick').textContent()
  await page.clock.runFor(2000)
  await expect(page.getByTestId('arcade-tick')).toHaveText(pausedTick!)
  await dialog.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByText('Checkpoint attempts: 2')).toBeVisible()
  await page.getByRole('button', { name: 'Restore arcade checkpoint' }).focus()
  await page.keyboard.press('Space')
  await expect(page.getByText('Arcade countdown: 3')).toBeVisible()
  await expect(page.getByTestId('arcade-tick')).toHaveText(pausedTick!)
  await page.clock.runFor(4000)
  expect(Number(await page.getByTestId('arcade-tick').textContent())).toBeGreaterThan(Number(pausedTick))
})
