import { expect, test } from '@playwright/test'

for (const width of [320, 390, 1280]) {
  test(`double battle keeps the single-battle scene and repeats its controls at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: width <= 390 ? 844 : 800 })
    await page.goto('/ui-test/doubles')
    await page.addStyleTag({ content: 'nextjs-portal { display: none !important; }' })

    await expect(page.getByRole('group', { name: 'Your Pokemon 1 health' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Your Pokemon 2 health' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Opponent Pokemon 1 health' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Opponent Pokemon 2 health' })).toBeVisible()
    await expect(page.getByText('Choose an action for each Pokemon')).toHaveCount(0)
    const firstHealth = await page.getByRole('group', { name: 'Your Pokemon 1 health' }).boundingBox()
    const secondHealth = await page.getByRole('group', { name: 'Your Pokemon 2 health' }).boundingBox()
    expect(secondHealth?.x).toBeGreaterThan(firstHealth?.x ?? 0)
    expect(Math.abs((secondHealth?.y ?? 0) - (firstHealth?.y ?? 0))).toBeLessThan(10)
    const playerSprite = await page.getByTestId('doubles-sprite-player-0').boundingBox()
    const enemySprite = await page.getByTestId('doubles-sprite-enemy-0').boundingBox()
    expect((playerSprite?.y ?? 0) - (enemySprite?.y ?? 0)).toBeGreaterThan(width <= 390 ? 30 : 60)
    await expect(page.getByTestId('selected-doubles-arrow')).toHaveCount(1)
    await expect(page.getByRole('button', { name: 'Items, 2 of 2 uses remaining' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Moves, 4 uses remaining' })).toBeVisible()
    await expect(page.getByText('Item · Potion')).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'SPEED' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'POWER' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'TECH' })).toBeVisible()
    await expect(page.getByTestId('battle-log-panel')).toHaveCSS('background-color', 'rgb(255, 248, 232)')
    await expect(page.getByTestId('selected-doubles-target-arrow')).toHaveCount(0)

    await page.screenshot({ path: `test-results/doubles-${width}-first.png` })
    const firstArrow = await page.getByTestId('selected-doubles-arrow').boundingBox()
    await page.getByRole('button', { name: 'POWER' }).click()
    await expect(page.getByRole('button', { name: 'Target Plusle' })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByTestId('selected-doubles-target-arrow')).toHaveCount(1)
    const firstTargetArrow = await page.getByTestId('selected-doubles-target-arrow').boundingBox()
    await page.getByRole('button', { name: 'Target Minun' }).click()
    await expect(page.getByRole('button', { name: 'Target Minun' })).toHaveAttribute('aria-pressed', 'true')
    const secondTargetArrow = await page.getByTestId('selected-doubles-target-arrow').boundingBox()
    expect(secondTargetArrow?.x).toBeGreaterThan(firstTargetArrow?.x ?? 0)
    await page.getByRole('button', { name: 'Target Plusle' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('button', { name: 'Target Plusle' })).toHaveAttribute('aria-pressed', 'true')
    await page.getByRole('button', { name: 'Target Minun' }).click()
    await expect(page.getByText('Target', { exact: true })).toHaveCount(0)
    await page.screenshot({ path: `test-results/doubles-${width}-target.png` })
    await page.getByRole('button', { name: 'Next Pokemon' }).click()
    await expect(page.getByRole('button', { name: 'Previous Pokemon' })).toBeVisible()
    const secondArrow = await page.getByTestId('selected-doubles-arrow').boundingBox()
    expect(secondArrow?.x).toBeGreaterThan(firstArrow?.x ?? 0)
    await expect(page.getByRole('button', { name: 'Moves, 4 uses remaining' })).toBeVisible()
    await page.getByRole('button', { name: 'TECH' }).click()
    await expect(page.getByRole('button', { name: 'Confirm turn' })).toBeEnabled()
    await page.screenshot({ path: `test-results/doubles-${width}-second.png` })

    const overflows = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
    expect(overflows).toBe(false)
  })
}

test('ally targets use the partner sprite while spread moves need no target arrow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/ui-test/doubles')
  await page.getByRole('button', { name: 'Moves, 4 uses remaining' }).click()
  await page.getByRole('button', { name: /Helping Hand/ }).click()
  await expect(page.getByRole('button', { name: 'Target Skeledirge' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Target Plusle' })).toHaveCount(0)
  await expect(page.getByTestId('selected-doubles-target-arrow')).toHaveCount(1)
  await page.getByRole('button', { name: 'Moves, 4 uses remaining' }).click()
  await page.getByRole('button', { name: /Heat Wave/ }).click()
  await expect(page.getByRole('button', { name: 'Target Skeledirge' })).toHaveCount(0)
  await expect(page.getByTestId('selected-doubles-target-arrow')).toHaveCount(0)
})
