import { expect, test } from '@playwright/test'

for (const width of [320, 390, 1280]) {
  test(`double battle keeps the single-battle scene and repeats its controls at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: width <= 390 ? 844 : 800 })
    await page.goto('/ui-test/doubles')
    await page.addStyleTag({ content: 'nextjs-portal { display: none !important; }' })

    await expect(page.getByRole('group', { name: 'Your Pokemon 1 health' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Your Pokemon 2 health' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Opponent Pokemon 1 health' })).toBeVisible()
    await expect(page.getByRole('group', { name: 'Opponent Pokemon 2 health' })).toBeVisible()
    await expect(page.getByText('Choose an action for each Pokemon')).toHaveCount(0)
    const firstHealth = await page.getByRole('group', { name: 'Your Pokemon 1 health' }).boundingBox()
    const secondHealth = await page.getByRole('group', { name: 'Your Pokemon 2 health' }).boundingBox()
    expect(secondHealth?.x).toBeGreaterThan(firstHealth?.x ?? 0)
    expect(Math.abs((secondHealth?.y ?? 0) - (firstHealth?.y ?? 0))).toBeLessThan(10)
    const playerSprite = await page.getByTestId('doubles-sprite-player-0').boundingBox()
    const enemySprite = await page.getByTestId('doubles-sprite-enemy-0').boundingBox()
    expect((playerSprite?.y ?? 0) - (enemySprite?.y ?? 0)).toBeGreaterThan(width <= 390 ? 30 : 60)
    const playerShadow = page.getByTestId('doubles-ground-shadow-player-0')
    const enemyShadow = page.getByTestId('doubles-ground-shadow-enemy-0')
    await expect(playerShadow).toHaveCSS('bottom', width <= 390 ? '12px' : '16px')
    await expect(enemyShadow).toHaveCSS('bottom', width <= 390 ? '20px' : '28px')
    expect((await playerShadow.boundingBox())?.width).toBe(width <= 390 ? 80 : 112)
    expect((await enemyShadow.boundingBox())?.width).toBe(width <= 390 ? 80 : 112)
    await expect(page.getByTestId('selected-doubles-arrow')).toHaveCount(1)
    await expect(page.getByRole('button', { name: 'Items' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Moves' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Stance' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Powers' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Switch' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Flee' })).toBeVisible()
    await expect(page.getByText('0/3 wins')).toHaveCount(0)
    if (width === 390) {
      await page.getByRole('button', { name: 'Powers' }).click()
      await expect(page.getByText('0/3 wins')).toBeVisible()
      await page.getByRole('button', { name: 'Back' }).click()
    }
    await expect(page.getByText('Item · Potion')).toHaveCount(0)
    await expect(page.getByTestId('battle-log-panel')).toHaveCSS('background-color', 'rgb(255, 248, 232)')
    await expect(page.getByTestId('selected-doubles-target-arrow')).toHaveCount(1)
    await expect(page.getByRole('button', { name: 'Target Plusle' })).toHaveAttribute('aria-pressed', 'true')

    await page.screenshot({ path: `test-results/doubles-${width}-first.png` })
    const firstArrow = await page.getByTestId('selected-doubles-arrow').boundingBox()
    const firstTargetArrow = await page.getByTestId('selected-doubles-target-arrow').boundingBox()
    await page.getByRole('button', { name: 'Target Minun' }).click()
    await expect(page.getByRole('button', { name: 'Target Minun' })).toHaveAttribute('aria-pressed', 'true')
    const secondTargetArrow = await page.getByTestId('selected-doubles-target-arrow').boundingBox()
    expect(secondTargetArrow?.x).toBeGreaterThan(firstTargetArrow?.x ?? 0)
    await page.getByRole('button', { name: 'Target Plusle' }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('button', { name: 'Target Plusle' })).toHaveAttribute('aria-pressed', 'true')
    await page.getByRole('button', { name: 'Target Minun' }).click()
    await expect(page.getByText('Target', { exact: true })).toHaveCount(0)
    await page.screenshot({ path: `test-results/doubles-${width}-target.png` })
    await page.getByRole('button', { name: 'Stance' }).click()
    await expect(page.getByRole('button', { name: /Power stance/ })).toBeVisible()
    await page.getByRole('button', { name: /Power stance/ }).click()
    const secondArrow = await page.getByTestId('selected-doubles-arrow').boundingBox()
    expect(secondArrow?.x).toBeGreaterThan(firstArrow?.x ?? 0)
    await expect(page.getByRole('button', { name: 'Moves' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Target Plusle' })).toHaveAttribute('aria-pressed', 'true')
    await page.getByRole('button', { name: 'Stance' }).click()
    await page.getByRole('button', { name: /Tech stance/ }).click()
    await expect(page.getByTestId('submitted-doubles-actions')).toContainText('"slot":1')
    await expect(page.getByTestId('submitted-doubles-actions')).toContainText('"slot":0')
    await expect(page.getByRole('button', { name: 'Confirm turn' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Next Pokemon' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Previous Pokemon' })).toHaveCount(0)
    await page.screenshot({ path: `test-results/doubles-${width}-second.png` })

    const overflows = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
    expect(overflows).toBe(false)
  })
}

test('move section matches singles and resolves ally/spread targeting automatically', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/ui-test/doubles')
  await page.getByRole('button', { name: 'Moves' }).click()
  await expect(page.getByText('4 left', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Moves' })).toBeVisible()
  await expect(page.getByText('Special Moves (4)')).toHaveCount(0)
  const helpingHand = page.getByRole('button', { name: 'Use Helping Hand' })
  const buttonBox = await helpingHand.boundingBox()
  expect(buttonBox).not.toBeNull()
  await page.mouse.move(buttonBox!.x + buttonBox!.width / 2, buttonBox!.y + buttonBox!.height / 2)
  await page.mouse.down()
  await page.waitForTimeout(650)
  await expect(page.getByText('Move field note')).toBeVisible()
  await expect(page.getByTestId('staged-doubles-actions')).toHaveText('{}')
  await page.mouse.up()
  await page.getByRole('button', { name: 'Back to moves' }).click()
  await page.getByRole('button', { name: 'Use Helping Hand' }).click()
  await expect(page.getByTestId('selected-doubles-arrow')).toHaveCount(1)
  await expect(page.getByTestId('staged-doubles-actions')).toContainText('"side":"ally"')
  await expect(page.getByTestId('selected-doubles-target-arrow')).toHaveCount(1)
  await page.getByRole('button', { name: 'Moves' }).click()
  await page.getByRole('button', { name: 'Use Heat Wave' }).click()
  await expect(page.getByTestId('submitted-doubles-actions')).toContainText('"moveId":"heat-wave"')
  await expect(page.getByTestId('submitted-doubles-actions')).toContainText('"side":"ally"')
  await expect(page.getByTestId('submitted-doubles-actions')).not.toContainText('"target":{"side":"opponent"')
})

test.describe('touch move details', () => {
  test.use({ hasTouch: true, isMobile: true })

  test('a long hold opens the field note without choosing the move', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/ui-test/doubles')
    await page.getByRole('button', { name: 'Moves' }).click()

    const move = page.getByRole('button', { name: 'Use Helping Hand' })
    const box = await move.boundingBox()
    expect(box).not.toBeNull()
    const touchPoint = { x: box!.x + box!.width / 2, y: box!.y + box!.height / 2 }
    const cdp = await page.context().newCDPSession(page)
    await cdp.send('Input.dispatchTouchEvent', {
      type: 'touchStart',
      touchPoints: [{ ...touchPoint, id: 1 }],
    })
    await expect(page.getByText('Move field note')).toBeVisible()
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect(page.getByTestId('staged-doubles-actions')).toHaveText('{}')
    await page.getByRole('button', { name: 'Back to moves' }).click()

    await move.focus()
    await page.keyboard.press('i')
    await expect(page.getByText('Move field note')).toBeVisible()
    await expect(page.getByTestId('staged-doubles-actions')).toHaveText('{}')
    await page.getByRole('button', { name: 'Back to moves' }).click()
    await move.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByTestId('staged-doubles-actions')).toContainText('"moveId":"helping-hand"')
  })
})

test('a submitted double turn animates the acting lanes and delays enemy HP changes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/ui-test/doubles')
  const plusle = page.getByRole('group', { name: 'Opponent Pokemon 1 health' }).getByRole('progressbar')
  const minun = page.getByRole('group', { name: 'Opponent Pokemon 2 health' }).getByRole('progressbar')
  await page.evaluate(() => {
    const browserWindow = window as typeof window & { doublesObservedActors?: string[] }
    browserWindow.doublesObservedActors = []
    const observer = new MutationObserver(() => {
      for (const slot of [0, 1]) {
        if (document.querySelector(`[data-testid="doubles-sprite-player-${slot}"] .translate-x-12`)) {
          const label = `player-${slot}`
          if (!browserWindow.doublesObservedActors?.includes(label)) browserWindow.doublesObservedActors?.push(label)
        }
      }
    })
    observer.observe(document.body, { attributes: true, childList: true, subtree: true })
  })
  await expect(plusle).toHaveAttribute('aria-valuenow', '100')
  await expect(minun).toHaveAttribute('aria-valuenow', '100')
  await page.getByRole('button', { name: 'Target Minun' }).click()
  await page.getByRole('button', { name: 'Stance' }).click()
  await page.getByRole('button', { name: /Power stance/ }).click()
  await page.getByRole('button', { name: 'Stance' }).click()
  await page.getByRole('button', { name: /Tech stance/ }).click()
  await expect(page.getByTestId('doubles-animation-processing')).toHaveText('true')
  await expect(plusle).toHaveAttribute('aria-valuenow', '100')
  await expect(minun).not.toHaveAttribute('aria-valuenow', '100')
  await expect(plusle).not.toHaveAttribute('aria-valuenow', '100')
  await expect(page.getByTestId('doubles-animation-processing')).toHaveText('false')
  const observedActors = await page.evaluate(() => (window as typeof window & { doublesObservedActors?: string[] }).doublesObservedActors)
  expect(observedActors).toEqual(['player-0', 'player-1'])
})

test('item section matches singles and chooses the next actor immediately', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/ui-test/doubles')
  await page.getByRole('button', { name: 'Items' }).click()
  await expect(page.getByText('2 left', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Items' })).toBeVisible()
  await expect(page.getByText('Battle Items')).toHaveCount(0)
  await expect(page.getByText('Healing')).toBeVisible()
  await expect(page.getByText('Heal 20 HP')).toBeVisible()
  await expect(page.getByText('×3')).toBeVisible()
  await page.getByRole('button', { name: /Potion/ }).click()
  await expect(page.getByTestId('submitted-doubles-actions')).toHaveText('[]')
  await expect(page.getByTestId('selected-doubles-arrow')).toHaveCount(1)
  await page.getByRole('button', { name: 'Stance' }).click()
  await page.getByRole('button', { name: /Power stance/ }).click()
  await expect(page.getByTestId('submitted-doubles-actions')).toContainText('"itemId":"battle-potion"')
})
