import { expect, test } from '@playwright/test'

for (const width of [390, 1280]) {
  test(`event authoring, scheduling and rarity controls at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 740 })
    await page.goto('/ui-test/events')
    await page.getByRole('button', { name: 'Create event', exact: true }).click()
    await page.getByLabel('Internal name').fill('Weekend outbreak')
    await page.getByLabel('Player title').fill('Route 1 outbreak')
    await page.getByLabel('Description', { exact: true }).fill('Discover unusual Pokémon this weekend.')
    await page.getByRole('button', { name: 'Content', exact: true }).click()
    await page.getByRole('button', { name: 'Capture encounter A place to find and catch Pokémon' }).click()
    await page.getByRole('button', { name: 'Create capture encounter from scratch' }).click()
    await page.getByLabel('Name', { exact: true }).fill('Event grass')
    await page.getByLabel('Description', { exact: true }).fill('Rustling grass')
    await page.getByLabel('Region', { exact: true }).fill('Kanto')
    await page.getByLabel('Search pokémon', { exact: true }).fill('Pika')
    await page.getByRole('button', { name: 'Pikachu #25' }).click()
    await expect(page.getByText('Pikachu', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Add Pokémon', exact: true }).click()
    await page.getByLabel('Search pokémon', { exact: true }).last().fill('Eevee')
    await page.getByRole('button', { name: 'Eevee #133' }).click()
    await expect(page.getByText('50.0% of the listed encounter pool')).toHaveCount(2)
    await page.getByLabel('Encounter weight', { exact: false }).last().fill('3')
    await expect(page.getByText('75.0% of the listed encounter pool')).toBeVisible()
    await page.screenshot({ path: `/tmp/event-roster-${width}.png` })
    await page.getByRole('button', { name: 'Set rarity chances', exact: true }).click()
    await page.getByLabel('Shadow (%)', { exact: true }).fill('10')
    await page.getByLabel('Silver (%)', { exact: true }).fill('1')
    await page.getByText('Resulting probabilities', { exact: false }).click()
    await expect(page.getByText('shadow: 9.0000%', { exact: true })).toBeVisible()
    const studio = page.getByRole('region', { name: 'Event studio' })
    await studio.evaluate((element) => { element.scrollTop = 0 })
    const viewport = await studio.boundingBox()
    if (!viewport) throw new Error('Event studio viewport is missing')
    await page.mouse.move(viewport.x + viewport.width / 2, viewport.y + viewport.height / 2)
    await page.mouse.wheel(0, 700)
    await expect.poll(() => studio.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
    await page.getByRole('button', { name: 'Save draft', exact: true }).scrollIntoViewIfNeeded()
    await expect(page.getByRole('button', { name: 'Save draft', exact: true })).toBeInViewport()
    expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(740)
    await page.getByRole('button', { name: 'Schedule', exact: true }).click()
    await page.getByLabel('Notify opted-in devices at activation').check()
    await page.getByLabel('Notification message').fill('The outbreak is here!')
    await page.getByRole('button', { name: 'Review', exact: true }).click()
    await expect(page.getByText('Route 1 outbreak', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Publish event', exact: true }).click()
    await expect(page.getByRole('status').filter({ hasText: 'Saved.' })).toBeVisible()
    await page.getByRole('button', { name: 'Back to events' }).click()
    await expect(page.getByText('Start notification enabled', { exact: false })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `/tmp/pokeori-event-studio-${width}.png` })
  })
}

for (const activity of ['Battle', 'Field research']) {
  test(`${activity} Pokémon can be selected and saved`, async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 740 })
    await page.goto('/ui-test/events')
    await page.getByRole('button', { name: 'Create event', exact: true }).click()
    await page.getByLabel('Internal name').fill('Roster check')
    await page.getByLabel('Player title').fill('A new adventure')
    await page.getByRole('button', { name: 'Continue to content' }).click()
    await page.getByRole('button', { name: activity === 'Battle' ? 'Battle A trainer challenge or wild battle' : 'Field research Pokémon to observe and study' }).click()
    await page.getByRole('button', { name: `Create ${activity.toLowerCase()} from scratch` }).click()
    await page.getByLabel('Name', { exact: true }).fill('Event activity')
    await page.getByLabel('Search pokémon', { exact: true }).fill('Pika')
    await page.getByRole('button', { name: 'Pikachu #25' }).click()
    await page.getByRole('button', { name: 'Save draft', exact: true }).click()
    await expect(page.getByRole('status').filter({ hasText: 'Saved.' })).toBeVisible()
    await page.getByRole('button', { name: 'Back to events' }).click()
    await page.getByRole('button', { name: 'Open', exact: true }).click()
    await page.getByRole('button', { name: 'Content', exact: true }).click()
    await expect(page.getByText('Pikachu', { exact: true })).toBeVisible()
  })
}
