import { expect, test } from '@playwright/test'

for (const width of [390, 1280]) {
  test(`event authoring, scheduling and rarity controls at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/ui-test/events')
    await page.getByRole('button', { name: 'Create event', exact: true }).click()
    await page.getByLabel('Internal name').fill('Weekend outbreak')
    await page.getByLabel('Player title').fill('Route 1 outbreak')
    await page.getByLabel('Description', { exact: true }).fill('Discover unusual Pokémon this weekend.')
    await page.getByRole('button', { name: 'Content', exact: true }).click()
    await page.getByLabel('Content type', { exact: true }).selectOption('location')
    await page.getByRole('button', { name: 'Create capture encounter from scratch' }).click()
    await page.getByLabel('name', { exact: true }).fill('Event grass')
    await page.getByLabel('description', { exact: true }).fill('Rustling grass')
    await page.getByLabel('category', { exact: true }).fill('Kanto')
    await page.getByLabel('id', { exact: true }).last().fill('poke-ball')
    await page.getByLabel('chance', { exact: true }).fill('100')
    await page.getByLabel('Add Capture encounter setting').selectOption('rarityChances')
    await page.getByLabel('Shadow (%)', { exact: true }).fill('10')
    await page.getByLabel('Silver (%)', { exact: true }).fill('1')
    await page.getByText('Resulting probabilities', { exact: false }).click()
    await expect(page.getByText('shadow: 9.0000%', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Schedule', exact: true }).click()
    await page.getByLabel('Notify opted-in devices at activation').check()
    await page.getByLabel('Notification message').fill('The outbreak is here!')
    await page.getByRole('button', { name: 'Review', exact: true }).click()
    await expect(page.getByText('Route 1 outbreak', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Publish event', exact: true }).click()
    await expect(page.getByRole('status')).toHaveText('Saved.')
    await page.getByRole('button', { name: 'Back to events' }).click()
    await expect(page.getByText('Start notification enabled', { exact: false })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `/tmp/pokeori-event-studio-${width}.png` })
  })
}
