/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pokemon: Pokemon;
    'expedition-runs': ExpeditionRun;
    'user-inventory-items': UserInventoryItem;
    'user-pokedex-entries': UserPokedexEntry;
    'user-abilitydex-entries': UserAbilitydexEntry;
    'user-task-progress': UserTaskProgress;
    'user-activity-stats': UserActivityStat;
    'user-tcg-cards': UserTcgCard;
    'user-shop-purchases': UserShopPurchase;
    'user-eggs': UserEgg;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      pokemon: 'pokemon';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pokemon: PokemonSelect<false> | PokemonSelect<true>;
    'expedition-runs': ExpeditionRunsSelect<false> | ExpeditionRunsSelect<true>;
    'user-inventory-items': UserInventoryItemsSelect<false> | UserInventoryItemsSelect<true>;
    'user-pokedex-entries': UserPokedexEntriesSelect<false> | UserPokedexEntriesSelect<true>;
    'user-abilitydex-entries': UserAbilitydexEntriesSelect<false> | UserAbilitydexEntriesSelect<true>;
    'user-task-progress': UserTaskProgressSelect<false> | UserTaskProgressSelect<true>;
    'user-activity-stats': UserActivityStatsSelect<false> | UserActivityStatsSelect<true>;
    'user-tcg-cards': UserTcgCardsSelect<false> | UserTcgCardsSelect<true>;
    'user-shop-purchases': UserShopPurchasesSelect<false> | UserShopPurchasesSelect<true>;
    'user-eggs': UserEggsSelect<false> | UserEggsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  isAdmin?: boolean | null;
  trainerName: string;
  /**
   * Currently active banner ID
   */
  banner?: string | null;
  /**
   * Currently active profile icon ID
   */
  icon?: string | null;
  /**
   * Currently active title ID
   */
  title?: string | null;
  /**
   * Array of unlocked banner IDs
   */
  unlockedBanners?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of unlocked icon IDs
   */
  unlockedIcons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of unlocked title IDs
   */
  unlockedTitles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  skills?: {
    catching?: {
      level?: number | null;
      exp?: number | null;
    };
    battling?: {
      level?: number | null;
      exp?: number | null;
    };
    researching?: {
      level?: number | null;
      exp?: number | null;
    };
    artisan?: {
      level?: number | null;
      exp?: number | null;
    };
    'ranked-battling'?: {
      level?: number | null;
      exp?: number | null;
    };
  };
  currency?: {
    crystals?: number | null;
    'mega-shards'?: number | null;
    pokedollars?: number | null;
    'battle-points'?: number | null;
    'berry-powder'?: number | null;
    'prof-scrip'?: number | null;
    'league-ticket'?: number | null;
  };
  /**
   * Maximum number of Pokemon this user can hold
   */
  maxPokemon?: number | null;
  /**
   * Maximum number of boxes this user can create
   */
  maxBoxes?: number | null;
  boxes?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable simplified UI for kids (e.g. sprites instead of text in quizzes)
   */
  kidMode?: boolean | null;
  powerUsage?: {
    /**
     * Number of times Tera has been used
     */
    teraUses?: number | null;
    /**
     * Number of times Mega Evolution has been used
     */
    megaEvolutionUses?: number | null;
    /**
     * Number of times Z-Moves have been used
     */
    zMoveUses?: number | null;
    /**
     * Number of times Dynamax has been used
     */
    dynamaxUses?: number | null;
    /**
     * Number of times Shouts have been used
     */
    shoutUses?: number | null;
    /**
     * Number of times Victory Power has been used
     */
    victoryUses?: number | null;
    /**
     * Number of times Weather Control has been used
     */
    weatherUses?: number | null;
    /**
     * Number of times Circadian Power has been used
     */
    circadianUses?: number | null;
    /**
     * Number of times Dimensional Shift has been used
     */
    dimensionalShiftUses?: number | null;
  };
  /**
   * Battle, Research, and Location statistics
   */
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Last time the random daily tasks were generated
   */
  lastDailyRefresh?: string | null;
  /**
   * Array of dynamically generated daily Task objects for today
   */
  activeDailyTasks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Saved TCG battle decks by format
   */
  tcgDecks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Saved TCG battle decks grouped by generation series, each with baby/champions/masters.
   */
  tcgDecksByGeneration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pokemon?: {
    docs?: (string | Pokemon)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * List of redeemed mystery gift codes
   */
  redeemedCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of user IDs who are confirmed friends
   */
  friends?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Friend request tracking with status
   */
  friendRequests?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User ID of the trainer selected as this player's rival
   */
  rivalTrainerId?: string | null;
  activeVoyages?:
    | {
        voyageId?: string | null;
        startTime?: string | null;
        endTime?: string | null;
        pokemonIds?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  voyageStats?: {
    totalCompleted?: number | null;
    completedVoyages?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Random roll used for event requirements (0-1,000,000)
   */
  lastRoll?: number | null;
  /**
   * Current weather slot for sub-region weather mapping (1-20)
   */
  weatherSlot?: number | null;
  /**
   * When the current weather slot was last rolled
   */
  weatherUpdatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pokemon".
 */
export interface Pokemon {
  id: string;
  user: string | User;
  originalTrainer: string | User;
  friendship?: number | null;
  name?: string | null;
  speciesId: number;
  formId: string;
  ability?: string | null;
  /**
   * Up to four eligible battle moves selected from owned move-granting TMs/HMs.
   */
  assignedMoves?:
    | {
        moveId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The only battle power this Pokemon can use. Leave empty to disable Pokemon Power usage.
   */
  selectedPokemonPower?:
    | ('tera' | 'mega' | 'z-move' | 'dynamax' | 'victory' | 'weather' | 'shout' | 'circadian' | 'dimensional-shift')
    | null;
  /**
   * Battle type applied by the Tera Orb. Tera Shards set this outside battle.
   */
  teraType?:
    | (
        | 'normal'
        | 'fire'
        | 'water'
        | 'electric'
        | 'grass'
        | 'ice'
        | 'fighting'
        | 'poison'
        | 'ground'
        | 'flying'
        | 'psychic'
        | 'bug'
        | 'rock'
        | 'ghost'
        | 'dragon'
        | 'dark'
        | 'steel'
        | 'fairy'
      )
    | null;
  /**
   * Inventory item currently held by this Pokemon. Held items are assigned from the Pokemon details modal.
   */
  heldItemId?: string | null;
  /**
   * Persistent percentage charge for held items that build energy through battle triggers.
   */
  itemCharge?: number | null;
  /**
   * Reusable key item that created the current fused form, when this Pokemon is fused.
   */
  fusionItemId?: string | null;
  /**
   * Original form to restore when this Pokemon is unfused.
   */
  fusionBaseFormId?: string | null;
  /**
   * Owned Pokemon ID hidden inside this visible fused Pokemon.
   */
  fusedWithPokemonId?: string | null;
  /**
   * Visible fused Pokemon ID this Pokemon is currently fused into.
   */
  fusedIntoPokemonId?: string | null;
  level: number;
  /**
   * Number of opposing Pokemon this Pokemon has knocked out in battles.
   */
  battleKOs?: number | null;
  stats?: {
    hp?: number | null;
    attack?: number | null;
    defense?: number | null;
    specialAttack?: number | null;
    specialDefense?: number | null;
    speed?: number | null;
  };
  ivs?: {
    hp?: number | null;
    attack?: number | null;
    defense?: number | null;
    specialAttack?: number | null;
    specialDefense?: number | null;
    speed?: number | null;
  };
  evs?: {
    hp?: number | null;
    attack?: number | null;
    defense?: number | null;
    specialAttack?: number | null;
    specialDefense?: number | null;
    speed?: number | null;
  };
  nature?: string | null;
  identified?: boolean | null;
  /**
   * A Pokémon can have exactly one rarity treatment. This controls its sprite and derives legacy Shiny, Shadow, and Radiant flags.
   */
  rarity?:
    | (
        | 'normal'
        | 'shiny'
        | 'shadow'
        | 'radiant'
        | 'silver'
        | 'gold'
        | 'emerald'
        | 'ruby'
        | 'sapphire'
        | 'crystal'
        | 'retro'
        | 'galactic'
        | 'levin'
        | 'inferno'
        | 'prism'
        | 'rainbow'
        | 'celestial'
        | 'black'
        | 'white'
        | 'void'
        | 'glitch'
        | 'ancient'
        | 'toxic'
      )
    | null;
  /**
   * Derived from the canonical rarity treatment.
   */
  shiny?: boolean | null;
  gender?: ('male' | 'female' | 'genderless') | null;
  /**
   * Derived from the canonical rarity treatment.
   */
  isShadow?: boolean | null;
  /**
   * Derived from the canonical rarity treatment.
   */
  isRadiant?: boolean | null;
  evolved?: boolean | null;
  height?: number | null;
  weight?: number | null;
  markingSquare?: boolean | null;
  markingCircle?: boolean | null;
  markingTriangle?: boolean | null;
  markingDiamond?: boolean | null;
  ballType?: string | null;
  /**
   * How this Pokemon was originally obtained.
   */
  obtainedMethod?: ('caught' | 'trade' | 'gift' | 'starter' | 'purchased' | 'reward' | 'hatched') | null;
  obtainedRegion?: string | null;
  obtainedLocation?: string | null;
  /**
   * Source activity/task/location ID that granted this Pokemon.
   */
  obtainedSourceId?: string | null;
  boxId?: string | null;
  locked?: boolean | null;
  size?: ('XS' | 'S' | 'L' | 'XL') | null;
  partner?: boolean | null;
  onBattleTeam?: boolean | null;
  battleTeamPosition?: number | null;
  isCompanion?: boolean | null;
  background?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expedition-runs".
 */
export interface ExpeditionRun {
  id: string;
  user: string | User;
  expeditionId: string;
  expeditionName: string;
  status: 'active' | 'ready_to_claim';
  mapItemId?: string | null;
  maxLosses: number;
  losses: number;
  currentStepIndex: number;
  totalSteps: number;
  steps:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt: string;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-inventory-items".
 */
export interface UserInventoryItem {
  id: string;
  user: string | User;
  itemId: string;
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-pokedex-entries".
 */
export interface UserPokedexEntry {
  id: string;
  user: string | User;
  speciesId: number;
  formId: string;
  seen?: boolean | null;
  caught?: boolean | null;
  totalSeen?: number | null;
  totalCaught?: number | null;
  shinySeen?: boolean | null;
  shinyCaught?: boolean | null;
  researchXp?: number | null;
  researchLevel?: number | null;
  preferredBattleStance?: ('power' | 'speed' | 'tech') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-abilitydex-entries".
 */
export interface UserAbilitydexEntry {
  id: string;
  user: string | User;
  abilityId: string;
  registered?: boolean | null;
  source?: string | null;
  firstRegisteredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-task-progress".
 */
export interface UserTaskProgress {
  id: string;
  user: string | User;
  taskId: string;
  count: number;
  completedAt?: string | null;
  lastCompletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-activity-stats".
 */
export interface UserActivityStat {
  id: string;
  user: string | User;
  activityType: 'battle' | 'research' | 'location' | 'expedition';
  activityId: string;
  wins: number;
  losses: number;
  highScore?: number | null;
  lastPlayed?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-tcg-cards".
 */
export interface UserTcgCard {
  id: string;
  user: string | User;
  cardId: string;
  setId?: string | null;
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-shop-purchases".
 */
export interface UserShopPurchase {
  id: string;
  user: string | User;
  shopItemId: string;
  shopId?: string | null;
  itemId?: string | null;
  count: number;
  firstPurchasedAt?: string | null;
  lastPurchasedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-eggs".
 */
export interface UserEgg {
  id: string;
  user: string | User;
  foundAt: string;
  hatchAt: string;
  sourceResearchId?: string | null;
  sourceBackground?: string | null;
  sourceRegion?: string | null;
  sourceLocation?: string | null;
  status: 'incubating' | 'hatched';
  hatchedPokemonId?: string | null;
  hatchPoolId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pokemon';
        value: string | Pokemon;
      } | null)
    | ({
        relationTo: 'expedition-runs';
        value: string | ExpeditionRun;
      } | null)
    | ({
        relationTo: 'user-inventory-items';
        value: string | UserInventoryItem;
      } | null)
    | ({
        relationTo: 'user-pokedex-entries';
        value: string | UserPokedexEntry;
      } | null)
    | ({
        relationTo: 'user-abilitydex-entries';
        value: string | UserAbilitydexEntry;
      } | null)
    | ({
        relationTo: 'user-task-progress';
        value: string | UserTaskProgress;
      } | null)
    | ({
        relationTo: 'user-activity-stats';
        value: string | UserActivityStat;
      } | null)
    | ({
        relationTo: 'user-tcg-cards';
        value: string | UserTcgCard;
      } | null)
    | ({
        relationTo: 'user-shop-purchases';
        value: string | UserShopPurchase;
      } | null)
    | ({
        relationTo: 'user-eggs';
        value: string | UserEgg;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  isAdmin?: T;
  trainerName?: T;
  banner?: T;
  icon?: T;
  title?: T;
  unlockedBanners?: T;
  unlockedIcons?: T;
  unlockedTitles?: T;
  skills?:
    | T
    | {
        catching?:
          | T
          | {
              level?: T;
              exp?: T;
            };
        battling?:
          | T
          | {
              level?: T;
              exp?: T;
            };
        researching?:
          | T
          | {
              level?: T;
              exp?: T;
            };
        artisan?:
          | T
          | {
              level?: T;
              exp?: T;
            };
        'ranked-battling'?:
          | T
          | {
              level?: T;
              exp?: T;
            };
      };
  currency?:
    | T
    | {
        crystals?: T;
        'mega-shards'?: T;
        pokedollars?: T;
        'battle-points'?: T;
        'berry-powder'?: T;
        'prof-scrip'?: T;
        'league-ticket'?: T;
      };
  maxPokemon?: T;
  maxBoxes?: T;
  boxes?:
    | T
    | {
        name?: T;
        id?: T;
      };
  kidMode?: T;
  powerUsage?:
    | T
    | {
        teraUses?: T;
        megaEvolutionUses?: T;
        zMoveUses?: T;
        dynamaxUses?: T;
        shoutUses?: T;
        victoryUses?: T;
        weatherUses?: T;
        circadianUses?: T;
        dimensionalShiftUses?: T;
      };
  stats?: T;
  lastDailyRefresh?: T;
  activeDailyTasks?: T;
  tcgDecks?: T;
  tcgDecksByGeneration?: T;
  pokemon?: T;
  redeemedCodes?: T;
  friends?: T;
  friendRequests?: T;
  rivalTrainerId?: T;
  activeVoyages?:
    | T
    | {
        voyageId?: T;
        startTime?: T;
        endTime?: T;
        pokemonIds?: T;
        id?: T;
      };
  voyageStats?:
    | T
    | {
        totalCompleted?: T;
        completedVoyages?: T;
      };
  lastRoll?: T;
  weatherSlot?: T;
  weatherUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pokemon_select".
 */
export interface PokemonSelect<T extends boolean = true> {
  user?: T;
  originalTrainer?: T;
  friendship?: T;
  name?: T;
  speciesId?: T;
  formId?: T;
  ability?: T;
  assignedMoves?:
    | T
    | {
        moveId?: T;
        id?: T;
      };
  selectedPokemonPower?: T;
  teraType?: T;
  heldItemId?: T;
  itemCharge?: T;
  fusionItemId?: T;
  fusionBaseFormId?: T;
  fusedWithPokemonId?: T;
  fusedIntoPokemonId?: T;
  level?: T;
  battleKOs?: T;
  stats?:
    | T
    | {
        hp?: T;
        attack?: T;
        defense?: T;
        specialAttack?: T;
        specialDefense?: T;
        speed?: T;
      };
  ivs?:
    | T
    | {
        hp?: T;
        attack?: T;
        defense?: T;
        specialAttack?: T;
        specialDefense?: T;
        speed?: T;
      };
  evs?:
    | T
    | {
        hp?: T;
        attack?: T;
        defense?: T;
        specialAttack?: T;
        specialDefense?: T;
        speed?: T;
      };
  nature?: T;
  identified?: T;
  rarity?: T;
  shiny?: T;
  gender?: T;
  isShadow?: T;
  isRadiant?: T;
  evolved?: T;
  height?: T;
  weight?: T;
  markingSquare?: T;
  markingCircle?: T;
  markingTriangle?: T;
  markingDiamond?: T;
  ballType?: T;
  obtainedMethod?: T;
  obtainedRegion?: T;
  obtainedLocation?: T;
  obtainedSourceId?: T;
  boxId?: T;
  locked?: T;
  size?: T;
  partner?: T;
  onBattleTeam?: T;
  battleTeamPosition?: T;
  isCompanion?: T;
  background?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expedition-runs_select".
 */
export interface ExpeditionRunsSelect<T extends boolean = true> {
  user?: T;
  expeditionId?: T;
  expeditionName?: T;
  status?: T;
  mapItemId?: T;
  maxLosses?: T;
  losses?: T;
  currentStepIndex?: T;
  totalSteps?: T;
  steps?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-inventory-items_select".
 */
export interface UserInventoryItemsSelect<T extends boolean = true> {
  user?: T;
  itemId?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-pokedex-entries_select".
 */
export interface UserPokedexEntriesSelect<T extends boolean = true> {
  user?: T;
  speciesId?: T;
  formId?: T;
  seen?: T;
  caught?: T;
  totalSeen?: T;
  totalCaught?: T;
  shinySeen?: T;
  shinyCaught?: T;
  researchXp?: T;
  researchLevel?: T;
  preferredBattleStance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-abilitydex-entries_select".
 */
export interface UserAbilitydexEntriesSelect<T extends boolean = true> {
  user?: T;
  abilityId?: T;
  registered?: T;
  source?: T;
  firstRegisteredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-task-progress_select".
 */
export interface UserTaskProgressSelect<T extends boolean = true> {
  user?: T;
  taskId?: T;
  count?: T;
  completedAt?: T;
  lastCompletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-activity-stats_select".
 */
export interface UserActivityStatsSelect<T extends boolean = true> {
  user?: T;
  activityType?: T;
  activityId?: T;
  wins?: T;
  losses?: T;
  highScore?: T;
  lastPlayed?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-tcg-cards_select".
 */
export interface UserTcgCardsSelect<T extends boolean = true> {
  user?: T;
  cardId?: T;
  setId?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-shop-purchases_select".
 */
export interface UserShopPurchasesSelect<T extends boolean = true> {
  user?: T;
  shopItemId?: T;
  shopId?: T;
  itemId?: T;
  count?: T;
  firstPurchasedAt?: T;
  lastPurchasedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-eggs_select".
 */
export interface UserEggsSelect<T extends boolean = true> {
  user?: T;
  foundAt?: T;
  hatchAt?: T;
  sourceResearchId?: T;
  sourceBackground?: T;
  sourceRegion?: T;
  sourceLocation?: T;
  status?: T;
  hatchedPokemonId?: T;
  hatchPoolId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}